name: Update rankings
on:
  schedule:
    - cron:  '30 10 * * *'
  workflow_dispatch:
jobs:
    resources:
        name: Update rankings
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                ref: master
            - uses: actions/setup-python@v4
              with:
                python-version: '3.13.x'
                cache: 'pip'
            - run: pip install -r requirements.txt
            - name: Scrape lodestone
              run: python main.py
            - name: Update repo with rankings
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: automated update
